site_name: nhisml
site_description: Survey-aware machine learning toolkit for NHIS Adults data
site_url: https://soda-lmu.github.io/nhisml/
repo_url: https://github.com/soda-lmu/nhisml
repo_name: soda-lmu/nhisml

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Command-line interface: cli.md
  - Python API: api.md
  - Reference statistics: reference_statistics.md
